[package]
name = "planning-budget-import"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
calamine = { version = "0.36.1", default-features = false }
planning-budget-core.workspace = true
thiserror = "2.0.21"
