//! Оболочка Tauri: состояние сессии, команды, события.

pub mod commands;
mod data_migration;
mod dto;
mod error;
mod events;
mod idle;
pub mod logging;
mod prefs;
mod recent;
pub mod self_test;
mod services;
mod state;
mod window;

use tauri::Manager as _;

pub use error::AppError;
pub use state::{AppPaths, AppState};

/// Сборщик команд и событий для tauri-specta.
#[must_use]
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(commands::registry::all())
        .events(tauri_specta::collect_events![
            events::VaultLocked,
            events::SystemThemeChanged,
            events::DataChanged
        ])
}

/// Генерирует `ui/src/lib/api/bindings.ts`.
///
/// # Errors
/// Если файл не удалось записать.
pub fn export_bindings(
    builder: &tauri_specta::Builder<tauri::Wry>,
) -> Result<(), specta_typescript::Error> {
    builder.export(
        specta_typescript::Typescript::default()
            .header("// @ts-nocheck\n// generated by tauri-specta: do not edit"),
        concat!(env!("CARGO_MANIFEST_DIR"), "/../ui/src/lib/api/bindings.ts"),
    )
}

/// Запуск приложения.
///
/// # Errors
/// Ошибка инициализации Tauri.
pub fn run() -> tauri::Result<()> {
    let builder = specta_builder();
    #[cfg(debug_assertions)]
    if let Err(err) = export_bindings(&builder) {
        tracing::warn!(%err, "bindings export failed");
    }
    tauri::Builder::default()
        // Первым в цепочке: второй процесс завершается, первое окно выходит вперёд.
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            window::focus_main(app);
        }))
        .plugin(tauri_plugin_window_state::Builder::default().build())
        // Диалоги открывает только Rust; фронтенду dialog:* не выдан.
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .on_window_event(window::on_event)
        .setup(move |app| {
            builder.mount_events(app);
            let data_dir = app.path().app_data_dir()?;
            let log_dir = data_dir.join("logs");
            std::fs::create_dir_all(&log_dir)?;
            app.manage(AppState::new(AppPaths::new(data_dir)));
            let guard = logging::init(&log_dir)?;
            app.manage(guard);
            let state = app.state::<AppState>();
            state.set_legacy_dir(
                data_migration::LEGACY_IDENTIFIER
                    .and_then(|id| data_migration::legacy_dir(state.paths().data_dir(), id)),
            );
            services::vault::run_migration(&state);
            idle::spawn_watcher(app.handle().clone())?;
            window::init(app.handle());
            Ok(())
        })
        .run(tauri::generate_context!())
}
