// @ts-nocheck
// generated by tauri-specta: do not edit
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Версия приложения. Пока единственная команда: нужна, чтобы `AppError` попал в биндинги. */
	appVersion: () => typedError<string, AppError>(__TAURI_INVOKE("app_version")),
	vaultStatus: () => typedError<VaultStatusDto, AppError>(__TAURI_INVOKE("vault_status")),
	vaultRetryMigration: () => typedError<VaultStatusDto, AppError>(__TAURI_INVOKE("vault_retry_migration")),
	vaultCreate: (password: Secret) => typedError<RecoveryCodeDto, AppError>(__TAURI_INVOKE("vault_create", { password })),
	vaultUnlock: (password: Secret) => typedError<{
	recoveryCode: string,
} | null, AppError>(__TAURI_INVOKE("vault_unlock", { password })),
	vaultUnlockRecovery: (code: Secret, newPassword: Secret) => typedError<{
	recoveryCode: string,
} | null, AppError>(__TAURI_INVOKE("vault_unlock_recovery", { code, newPassword })),
	vaultChangePassword: (oldPassword: Secret, newPassword: Secret) => typedError<null, AppError>(__TAURI_INVOKE("vault_change_password", { oldPassword, newPassword })),
	/**  Перевыпуск ключа шифрования: нужен открытый сейф. Возвращает новый recovery-код. */
	vaultRekey: (password: Secret) => typedError<RecoveryCodeDto, AppError>(__TAURI_INVOKE("vault_rekey", { password })),
	vaultLock: () => typedError<null, AppError>(__TAURI_INVOKE("vault_lock")),
	vaultReset: (password: Secret, confirmPhrase: string) => typedError<null, AppError>(__TAURI_INVOKE("vault_reset", { password, confirmPhrase })),
	/**  Сохранение recovery-кода в файл. Диалог открывает Rust: путь из WebView не принимается. */
	vaultSaveRecoveryCode: (code: Secret) => typedError<SavedDto, AppError>(__TAURI_INVOKE("vault_save_recovery_code", { code })),
	/**  Сброс таймера автоблокировки. Фронтенд шлёт на `pointerdown` и `keydown` не чаще раза в 30 с. */
	activityPing: () => typedError<null, AppError>(__TAURI_INVOKE("activity_ping")),
	prefsGet: () => typedError<Prefs, AppError>(__TAURI_INVOKE("prefs_get")),
	/**
	 *  Тёмная ли тема у окна. В режиме «системная» это тема ОС; изменения приходят событием
	 *  `SystemThemeChanged`.
	 */
	systemDark: () => typedError<boolean, AppError>(__TAURI_INVOKE("system_dark")),
	prefsSet: (patch: PrefsPatch) => typedError<Prefs, AppError>(__TAURI_INVOKE("prefs_set", { patch })),
	categoriesList: (includeArchived: boolean) => typedError<CategoryDto[], AppError>(__TAURI_INVOKE("categories_list", { includeArchived })),
	categoriesCreate: (input: CategoryInput) => typedError<CategoryDto, AppError>(__TAURI_INVOKE("categories_create", { input })),
	categoriesUpdate: (id: Int53, patch: CategoryPatchDto_Deserialize) => typedError<CategoryDto, AppError>(__TAURI_INVOKE("categories_update", { id, patch })),
	categoriesArchive: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("categories_archive", { id })),
	categoriesUnarchive: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("categories_unarchive", { id })),
	categoriesDelete: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("categories_delete", { id })),
	categoriesReorder: (ids: Int53[]) => typedError<CategoryDto[], AppError>(__TAURI_INVOKE("categories_reorder", { ids })),
	limitsSet: (categoryId: Int53, validFrom: string, amount: Int53) => typedError<null, AppError>(__TAURI_INVOKE("limits_set", { categoryId, validFrom, amount })),
	limitsUnset: (categoryId: Int53, validFrom: string) => typedError<null, AppError>(__TAURI_INVOKE("limits_unset", { categoryId, validFrom })),
	limitsClear: (categoryId: Int53, validFrom: string) => typedError<null, AppError>(__TAURI_INVOKE("limits_clear", { categoryId, validFrom })),
	limitsHistory: (categoryId: Int53) => typedError<LimitEntryDto[], AppError>(__TAURI_INVOKE("limits_history", { categoryId })),
	savingsRateSet: (categoryId: Int53, validFrom: string, rateBp: number) => typedError<null, AppError>(__TAURI_INVOKE("savings_rate_set", { categoryId, validFrom, rateBp })),
	savingsOverrideSet: (month: string, categoryId: Int53, rateBp: number) => typedError<null, AppError>(__TAURI_INVOKE("savings_override_set", { month, categoryId, rateBp })),
	savingsOverrideClear: (month: string, categoryId: Int53) => typedError<null, AppError>(__TAURI_INVOKE("savings_override_clear", { month, categoryId })),
	txList: (month: string) => typedError<TransactionDto[], AppError>(__TAURI_INVOKE("tx_list", { month })),
	txCreate: (requestId: string, input: TransactionInput) => typedError<TransactionDto, AppError>(__TAURI_INVOKE("tx_create", { requestId, input })),
	txUpdate: (id: Int53, patch: TransactionPatchDto_Deserialize) => typedError<TxUpdateResultDto, AppError>(__TAURI_INVOKE("tx_update", { id, patch })),
	txSetStatus: (id: Int53, status: TxStatusDto) => typedError<TxUpdateResultDto, AppError>(__TAURI_INVOKE("tx_set_status", { id, status })),
	txDelete: (id: Int53) => typedError<TransactionDto, AppError>(__TAURI_INVOKE("tx_delete", { id })),
	txRestore: (id: Int53) => typedError<TransactionDto, AppError>(__TAURI_INVOKE("tx_restore", { id })),
	txTagsSet: (id: Int53, tagIds: Int53[]) => typedError<TransactionDto, AppError>(__TAURI_INVOKE("tx_tags_set", { id, tagIds })),
	tagsList: () => typedError<TagDto[], AppError>(__TAURI_INVOKE("tags_list")),
	tagsCreate: (name: string) => typedError<TagDto, AppError>(__TAURI_INVOKE("tags_create", { name })),
	incomesList: (month: string) => typedError<IncomeDto[], AppError>(__TAURI_INVOKE("incomes_list", { month })),
	incomesCreate: (input: IncomeInput) => typedError<IncomeDto, AppError>(__TAURI_INVOKE("incomes_create", { input })),
	incomesUpdate: (id: Int53, patch: IncomePatchDto_Deserialize) => typedError<IncomeUpdateResultDto, AppError>(__TAURI_INVOKE("incomes_update", { id, patch })),
	incomesDelete: (id: Int53) => typedError<IncomeDto, AppError>(__TAURI_INVOKE("incomes_delete", { id })),
	incomesRestore: (id: Int53) => typedError<IncomeDto, AppError>(__TAURI_INVOKE("incomes_restore", { id })),
	search: (query: string, requestId: number) => typedError<SearchResultDto, AppError>(__TAURI_INVOKE("search", { query, requestId })),
	/**  Разбор строки запроса для чипов (фильтр графика). Данных бюджета не читает. */
	queryParse: (query: string) => typedError<QueryParseDto, AppError>(__TAURI_INVOKE("query_parse", { query })),
	txSearch: (query: string, requestId: number) => typedError<TransactionSearchDto, AppError>(__TAURI_INVOKE("tx_search", { query, requestId })),
	incomesSearch: (query: string, requestId: number) => typedError<IncomeSearchDto, AppError>(__TAURI_INVOKE("incomes_search", { query, requestId })),
	filtersList: () => typedError<SavedFilterDto[], AppError>(__TAURI_INVOKE("filters_list")),
	filtersSave: (name: string, query: string, screen: FilterScreenDto) => typedError<SavedFilterDto, AppError>(__TAURI_INVOKE("filters_save", { name, query, screen })),
	filtersDelete: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("filters_delete", { id })),
	txSuggest: (query: string) => typedError<TitleSuggestionDto[], AppError>(__TAURI_INVOKE("tx_suggest", { query })),
	txCategoryUsage: () => typedError<CategoryUsageDto[], AppError>(__TAURI_INVOKE("tx_category_usage")),
	analyticsRun: (spec: ChartSpecDto) => typedError<ChartDataDto, AppError>(__TAURI_INVOKE("analytics_run", { spec })),
	analyticsRunMany: (specs: ChartSpecDto[]) => typedError<ChartRunDto[], AppError>(__TAURI_INVOKE("analytics_run_many", { specs })),
	analyticsCheck: (specs: ChartSpecDto[]) => typedError<(string | null)[], AppError>(__TAURI_INVOKE("analytics_check", { specs })),
	dashboardsList: () => typedError<DashboardDto[], AppError>(__TAURI_INVOKE("dashboards_list")),
	dashboardsCreate: (name: string) => typedError<DashboardDto, AppError>(__TAURI_INVOKE("dashboards_create", { name })),
	dashboardsCreateDefault: () => typedError<DashboardDto, AppError>(__TAURI_INVOKE("dashboards_create_default")),
	dashboardsRename: (id: Int53, name: string) => typedError<null, AppError>(__TAURI_INVOKE("dashboards_rename", { id, name })),
	dashboardsDelete: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("dashboards_delete", { id })),
	chartsList: (dashboardId: Int53) => typedError<ChartCardDto[], AppError>(__TAURI_INVOKE("charts_list", { dashboardId })),
	chartsCreate: (dashboardId: Int53, spec: ChartSpecDto, w: number, h: number) => typedError<ChartCardDto, AppError>(__TAURI_INVOKE("charts_create", { dashboardId, spec, w, h })),
	chartsUpdate: (id: Int53, spec: ChartSpecDto) => typedError<ChartCardDto, AppError>(__TAURI_INVOKE("charts_update", { id, spec })),
	chartsDelete: (id: Int53) => typedError<null, AppError>(__TAURI_INVOKE("charts_delete", { id })),
	chartsLayoutSet: (dashboardId: Int53, placements: CardPlacementDto[]) => typedError<null, AppError>(__TAURI_INVOKE("charts_layout_set", { dashboardId, placements })),
	/**  Накопления года: факт, прогноз, итоги и готовые графики. */
	savingsOverview: (year: number) => typedError<SavingsOverviewDto, AppError>(__TAURI_INVOKE("savings_overview", { year })),
	/**  Ставка, налог, стартовый баланс и месяц начала накопления. */
	savingsParamsSet: (categoryId: Int53, params: SavingsParamsDto) => typedError<null, AppError>(__TAURI_INVOKE("savings_params_set", { categoryId, params })),
	/**  Фиксированный план накопления в месяц с `valid_from` (вместо процента от дохода). */
	savingsFixedSet: (categoryId: Int53, validFrom: string, amount: Int53) => typedError<null, AppError>(__TAURI_INVOKE("savings_fixed_set", { categoryId, validFrom, amount })),
	debtsList: (month: string, includeClosed: boolean) => typedError<DebtsOverviewDto, AppError>(__TAURI_INVOKE("debts_list", { month, includeClosed })),
	debtsCreate: (input: DebtInput) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debts_create", { input })),
	/**  Долг из траты со статусом «Долг»: сумма, статья и месяц берутся из траты. */
	debtFromTx: (txId: Int53, lender: string, schedule: SchedulePaymentDto[]) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debt_from_tx", { txId, lender, schedule })),
	debtsUpdate: (id: Int53, patch: DebtPatchDto_Deserialize) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debts_update", { id, patch })),
	debtsDelete: (id: Int53) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debts_delete", { id })),
	debtsRestore: (id: Int53) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debts_restore", { id })),
	/**  Отметить строку графика оплаченной или вернуть её в план. */
	debtPaymentSetStatus: (paymentId: Int53, status: DebtPaymentStatusDto, paidDate: string | null) => typedError<DebtDto, AppError>(__TAURI_INVOKE("debt_payment_set_status", { paymentId, status, paidDate })),
	/**  Быстрый график погашения: считает Rust, данные не читаются, но сессия нужна. */
	debtSchedulePreview: (amount: Int53, takenMonth: string, kind: DebtScheduleKindDto) => typedError<SchedulePreviewDto, AppError>(__TAURI_INVOKE("debt_schedule_preview", { amount, takenMonth, kind })),
	planMonth: (month: string) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_month", { month })),
	/**  «План готов»: фиксирует плановые суммы месяца. */
	planLock: (month: string) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_lock", { month })),
	/**  Снимает фиксацию плана. */
	planUnlock: (month: string) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_unlock", { month })),
	/**  «Скопировать план из прошлого месяца» в `month`. */
	planCopyFromPrevious: (month: string) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_copy_from_previous", { month })),
	/**  Предпросмотр мастера первого месяца: «Не распределено» по введённому, без записи. */
	planPreview: (month: string, input: PlanWizardInputDto) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_preview", { month, input })),
	/**  Мастер первого месяца: доходы, плановые траты и план накоплений, затем «План готов». */
	planWizardApply: (month: string, input: PlanWizardInputDto) => typedError<MonthPlanDto, AppError>(__TAURI_INVOKE("plan_wizard_apply", { month, input })),
	summaryMonth: (month: string) => typedError<MonthOverviewDto, AppError>(__TAURI_INVOKE("summary_month", { month })),
	summarySeries: (month: string, range: SeriesRangeDto) => typedError<MonthSummaryDto[], AppError>(__TAURI_INVOKE("summary_series", { month, range })),
	summaryYear: (year: number) => typedError<YearSummaryDto, AppError>(__TAURI_INVOKE("summary_year", { year })),
	settingsGet: () => typedError<SettingsDto, AppError>(__TAURI_INVOKE("settings_get")),
	settingsSet: (patch: SettingsPatchDto) => typedError<SettingsDto, AppError>(__TAURI_INVOKE("settings_set", { patch })),
	/**
	 *  Открывает диалог выбора `.xlsx`, переносит данные и возвращает отчёт сверки.
	 *  `null`, если пользователь закрыл диалог.
	 */
	legacyImport: () => typedError<{
	categoriesCreated: number,
	categoriesMatched: number,
	kindConflicts: string[],
	limitsWritten: number,
	transactions: number,
	incomes: number,
	settingsApplied: boolean,
	blockMismatches: BlockMismatchDto[],
	/**  `null`, если итоги посчитать не удалось: данные при этом записаны. */
	totals: LegacyTotalsDto | null,
} | null, AppError>(__TAURI_INVOKE("legacy_import")),
	/**  Заливает `seed-2026.json` в пустую базу. */
	devSeed: () => typedError<null, AppError>(__TAURI_INVOKE("dev_seed")),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	systemThemeChanged: makeEvent<SystemThemeChanged>("system-theme-changed"),
	vaultLocked: makeEvent<VaultLocked>("vault-locked"),
};

/* Types */
/**  Одно накопление: параметры, план, факт и прогноз; графики готовы к показу. */
export type AccumulationDto = {
	categoryId: number,
	params: SavingsParamsDto,
	planKind: SavingsPlanKindDto,
	/**  Процент плана от дохода, базисные пункты (при `planKind = percent`). */
	planRateBp: number,
	/**  Фиксированная сумма плана в месяц (при `planKind = fixed`). */
	planFixed: number | null,
	/**  План взноса в текущем месяце. */
	plan: number,
	/**  Баланс на конец декабря года. */
	balance: number,
	/**  Ставка после налога на купон, базисные пункты: 1600 при налоге 1300 дают 1392. */
	effectiveRateBp: number,
	months: SavingsMonthDto[],
	scenarios: ForecastScenarioDto[],
	/**  Линии «Баланс» и «Внесено» по месяцам года. */
	factChart: ChartDataDto,
	/**  Линии сценариев A/B/C на 60 месяцев. */
	forecastChart: ChartDataDto,
};

export type AppError = { code: "Locked" } | { code: "WrongPassword"; retryAfterMs: number } | 
/**  Попытка в окне задержки: пароль не проверялся. */
{ code: "TooManyAttempts"; retryAfterMs: number } | { code: "Validation"; messageKey: string; field: string | null } | { code: "NotFound"; entity: string; id: number } | { code: "Conflict"; messageKey: string } | { code: "Import"; messageKey: string; line: number | null } | { code: "Io"; messageKey: string } | { code: "Internal"; correlationId: string };

/**  Блок категории, у которого «Итого» в таблице не равно сумме позиций. */
export type BlockMismatchDto = {
	month: string,
	category: string,
	declared: number,
	parsed: number,
};

/**  «Баланс бюджета». */
export type BudgetBalanceDto = {
	avgIncome: number,
	savingsTarget: number,
	limitsSum: number,
	buffer: number,
	bufferRate: number | null,
	economy: number,
};

export type CardPlacementDto = {
	id: Int53,
	x: number,
	y: number,
	w: number,
	h: number,
};

export type CategoryDto = {
	id: number,
	name: string,
	kind: CategoryKindDto,
	color: string,
	sortOrder: number,
	note: string | null,
	archived: boolean,
};

export type CategoryHitDto = {
	id: number,
	name: string,
};

export type CategoryInput = {
	name: string,
	kind: CategoryKindDto,
	color: string,
	note: string | null,
};

export type CategoryKindDto = "mandatory" | "wants" | "savings" | "loans";

/**  Правка категории: отсутствующее поле не меняется; `note: null` очищает заметку. */
export type CategoryPatchDto = CategoryPatchDto_Serialize | CategoryPatchDto_Deserialize;

/**  Правка категории: отсутствующее поле не меняется; `note: null` очищает заметку. */
export type CategoryPatchDto_Deserialize = {
	name?: string | null,
	color?: string | null,
	note?: string | null,
};

/**  Правка категории: отсутствующее поле не меняется; `note: null` очищает заметку. */
export type CategoryPatchDto_Serialize = {
	name: string | null,
	color: string | null,
	note: string | null,
};

export type CategoryUsageDto = {
	categoryId: number,
	uses: number,
};

export type CategoryYearRowDto = {
	categoryId: number,
	total: number,
	avg: number,
	limitNow: number | null,
	avgMinusLimit: number | null,
	shareInExpenses: number | null,
};

/**  Что изменилось: по области фронтенд сбрасывает нужные кэши. */
export type ChangeScope = "categories" | "limits" | "savings" | "transactions" | "incomes" | "tags" | "settings" | 
/**  План месяца: фиксация, разблокировка, копирование. */
"plan" | 
/**  Долги и графики погашений. */
"debts" | 
/**  Данные заменены целиком (dev-сид, будущий импорт xlsx): перечитать всё. */
"all";

/**  Карточка графика на сетке из 12 колонок; высота ячейки 80 px. */
export type ChartCardDto = {
	id: number,
	dashboardId: number,
	spec: ChartSpecDto,
	x: number,
	y: number,
	w: number,
	h: number,
};

export type ChartDataDto = {
	categories: string[],
	categoryTokens: string[],
	series: ChartSeriesDto[],
	referenceLines: ChartRefLineDto[],
	totals: (number | null)[] | null,
	unit: ChartUnitDto,
};

export type ChartGroupByDto = "month" | "category" | "kind" | "status" | "tag" | "none";

export type ChartMetricDto = "spent" | "expenses" | "income" | "savings" | "free" | "free_cum" | "savings_cum" | "savings_rate" | "limit_usage" | "count" | "avg_ticket";

export type ChartOptionsDto = {
	showLimit: boolean,
	topN: number | null,
	sort: ChartSortDto,
	cumulative: boolean,
	comparePrevPeriod: boolean,
	percent: boolean,
};

export type ChartPeriodDto = ({ preset: PeriodPresetDto }) & { from?: never; to?: never } | ({ from: string; to: string }) & { preset?: never };

export type ChartRefLineDto = {
	name: string,
	from: number | null,
	to: number | null,
};

/**
 *  Результат одного графика пакетного расчёта: либо данные, либо ключ причины
 *  (`errors.chart.<причина>`), чтобы один недопустимый график не ронял остальные.
 */
export type ChartRunDto = {
	data: ChartDataDto | null,
	errorKey: string | null,
};

export type ChartSeriesByDto = "status" | "kind" | "category" | "metric";

export type ChartSeriesDto = {
	name: string,
	color: string,
	values: (number | null)[],
};

export type ChartSortDto = "desc" | "asc" | "natural";

/**  `ChartSpec` v1; в базе лежит JSON `planning_budget_core::analytics::ChartSpec`. */
export type ChartSpecDto = {
	version: number,
	title: string,
	type: ChartTypeDto,
	metric: ChartMetricDto,
	groupBy: ChartGroupByDto,
	seriesBy: ChartSeriesByDto | null,
	metrics: ChartMetricDto[],
	period: ChartPeriodDto,
	filter: string,
	options: ChartOptionsDto,
};

export type ChartTypeDto = "bar" | "stacked_bar" | "hbar" | "line" | "area" | "donut" | "table" | "kpi";

export type ChartUnitDto = "rub" | "percent" | "count";

export type CorridorDto = "noIncome" | "below" | "within" | "above";

export type DashboardDto = {
	id: number,
	name: string,
	isDefault: boolean,
};

/**
 *  Данные бюджета изменились. `months` — затронутые месяцы `YYYY-MM`; пустой список
 *  означает «не привязано к месяцу» (категории, теги, настройки) или «все месяцы».
 */
export type DataChanged = {
	scope: ChangeScope,
	months: string[],
};

/**  Долг со всем графиком; остаток и доля погашения посчитаны в Rust. */
export type DebtDto = {
	id: number,
	lender: string,
	amount: number,
	takenMonth: string,
	takenDate: string | null,
	categoryId: number | null,
	transactionId: number | null,
	comment: string | null,
	/**  Все платежи оплачены. */
	closed: boolean,
	remaining: number,
	/**  Доля погашенного в базисных пунктах (10 000 = долг закрыт). */
	paidBp: number,
	nextPayment: DebtPaymentDto | null,
	payments: DebtPaymentDto[],
};

/**  Новый долг; сумма графика должна равняться сумме долга. */
export type DebtInput = {
	lender: string,
	amount: number,
	takenMonth: string,
	takenDate: string | null,
	categoryId: number | null,
	comment: string | null,
	schedule: SchedulePaymentDto[],
};

/**
 *  Правка долга: отсутствующее поле не меняется; `categoryId`/`comment: null` очищают значение.
 *  `schedule` заменяет только неоплаченные строки.
 */
export type DebtPatchDto = DebtPatchDto_Serialize | DebtPatchDto_Deserialize;

/**
 *  Правка долга: отсутствующее поле не меняется; `categoryId`/`comment: null` очищают значение.
 *  `schedule` заменяет только неоплаченные строки.
 */
export type DebtPatchDto_Deserialize = {
	lender?: string | null,
	amount?: number | null,
	categoryId?: number | null,
	comment?: string | null,
	schedule?: SchedulePaymentDto[] | null,
};

/**
 *  Правка долга: отсутствующее поле не меняется; `categoryId`/`comment: null` очищают значение.
 *  `schedule` заменяет только неоплаченные строки.
 */
export type DebtPatchDto_Serialize = {
	lender: string | null,
	amount: number | null,
	categoryId: number | null,
	comment: string | null,
	schedule: SchedulePaymentDto[] | null,
};

/**  Строка графика погашения. */
export type DebtPaymentDto = {
	id: number,
	month: string,
	amount: number,
	status: DebtPaymentStatusDto,
	paidDate: string | null,
};

/**  Статус строки графика. */
export type DebtPaymentStatusDto = "planned" | "paid";

/**  Быстрый график погашения (считает Rust). */
export type DebtScheduleKindDto = 
/**  Равными частями на `months` месяцев, начиная со следующего за месяцем займа. */
{ kind: "equalParts"; months: number } | 
/**  Одним платежом в месяце `month`. */
{ kind: "single"; month: string };

/**  Раздел «Долги» на месяц: список и итоги. */
export type DebtsOverviewDto = {
	debts: DebtDto[],
	openCount: number,
	closedCount: number,
	/**  Сумма остатков открытых долгов. */
	remainingTotal: number,
	/**  К оплате в месяце (все строки графиков месяца). */
	paymentsPlanned: number,
	/**  Из них оплачено. */
	paymentsPaid: number,
};

/**  Экран сохранённого фильтра: «Расходы» или «Доходы». */
export type FilterScreenDto = "expenses" | "incomes";

export type ForecastKindDto = "a" | "b" | "c";

export type ForecastScenarioDto = {
	scenario: ForecastKindDto,
	/**  Название сценария для таблиц и легенды: «A · цель нормы». */
	name: string,
	contribution: number,
	y1: number,
	y3: number,
	y5: number,
	coupons60: number,
	/**  Баланс на конец каждого из 60 месяцев: точки линии прогноза. */
	balances: number[],
};

export type IncomeDto = {
	id: number,
	month: string,
	date: string | null,
	sourceName: string,
	amount: number,
	status: IncomeStatusDto,
	comment: string | null,
};

export type IncomeGroupDto = {
	total: number,
	sum: number,
	items: IncomeHitDto[],
};

export type IncomeHitDto = {
	id: number,
	sourceName: string,
	month: string,
	date: string | null,
	amount: number,
	status: IncomeStatusDto,
};

export type IncomeInput = {
	month: string,
	date: string | null,
	sourceName: string,
	amount: number,
	status: IncomeStatusDto,
	comment: string | null,
};

export type IncomePatchDto = IncomePatchDto_Serialize | IncomePatchDto_Deserialize;

export type IncomePatchDto_Deserialize = {
	month?: string | null,
	date?: string | null,
	sourceName?: string | null,
	amount?: number | null,
	status?: IncomeStatusDto | null,
	comment?: string | null,
};

export type IncomePatchDto_Serialize = {
	month: string | null,
	date: string | null,
	sourceName: string | null,
	amount: number | null,
	status: IncomeStatusDto | null,
	comment: string | null,
};

export type IncomeSearchDto = {
	requestId: number,
	spans: TokenSpanDto[],
	hints: QueryHintSpanDto[],
	total: number,
	sum: number,
	truncated: boolean,
	items: IncomeDto[],
};

export type IncomeStatusDto = "received" | "expected";

export type IncomeUpdateResultDto = {
	current: IncomeDto,
	previous: IncomeDto,
};

/**
 *  Целое из JS `number` (id, копейки < 2^53) в аргументах команд: tauri-specta не принимает
 *  `i64` как есть, а в TS нужен `number`, а не `bigint`.
 */
export type Int53 = number;

export type KindAmountsDto = {
	mandatory: number,
	wants: number,
	savings: number,
	loans: number,
};

/**  Отчёт переноса из старой таблицы. */
export type LegacyReportDto = {
	categoriesCreated: number,
	categoriesMatched: number,
	kindConflicts: string[],
	limitsWritten: number,
	transactions: number,
	incomes: number,
	settingsApplied: boolean,
	blockMismatches: BlockMismatchDto[],
	/**  `null`, если итоги посчитать не удалось: данные при этом записаны. */
	totals: LegacyTotalsDto | null,
};

/**  Итоги года по данным базы после переноса: их пользователь сверяет со своей таблицей. */
export type LegacyTotalsDto = {
	year: number,
	income: number,
	expenses: number,
	savings: number,
	free: number,
	monthsWithData: number,
};

export type LimitEntryDto = {
	validFrom: string,
	/**  `None` — «лимита нет с этого месяца». */
	amount: number | null,
};

export type LimitLevelDto = "ok" | "warn" | "over";

/**  Категория в месяце: факт против лимита. */
export type LimitRowDto = {
	categoryId: number,
	fact: number,
	limit: number | null,
	remaining: number | null,
	usage: number | null,
	/**  `usage` в целых процентах. */
	usagePercent: number | null,
	/**  Только у накоплений: процент плана по истории на месяц (без ручного значения месяца). */
	planRateBp: number | null,
	/**  Доля лимита, занятая оплаченным; `None` без лимита. */
	paidUsage: number | null,
	/**  Доля лимита, занятая планом. */
	plannedUsage: number | null,
	level: LimitLevelDto | null,
	byStatus: StatusAmountsDto,
};

export type LockReason = "manual" | "idle" | 
/**  Окно свёрнуто при включённой опции «блокировать при сворачивании». */
"minimize";

export type MonthHitDto = {
	month: string,
	records: number,
};

/**  Данные экрана «Обзор» за месяц. */
export type MonthOverviewDto = {
	summary: MonthSummaryDto,
	limits: LimitRowDto[],
	limitsTotal: number,
	limitsRemaining: number,
	spentVsLimits: number | null,
	/**  Категорий выше лимита. */
	overCount: number,
	/**  План месяца зафиксирован («План готов»): новые траты по умолчанию «Незапланировано». */
	planLocked: boolean,
	/**  Расходы месяца к среднему за год в целых процентах; `None`, если сравнивать не с чем. */
	expensesDeltaPercent: number | null,
};

/**  План месяца: все числа посчитаны в Rust. */
export type MonthPlanDto = {
	month: string,
	/**  Месяц зафиксирован кнопкой «План готов». */
	locked: boolean,
	income: number,
	planExpenses: number,
	planSavings: number,
	planRepayments: number,
	/**  `income − plan_expenses − plan_savings − plan_repayments`. */
	unallocated: number,
	balance: PlanBalanceDto,
	rows: PlanRowDto[],
	/**  Погашения долгов этого месяца. */
	repayments: PlanRepaymentDto[],
	/**  Траты со статусом «Незапланировано». */
	unplanned: number,
	/**  Взято в долг в этом месяце. */
	borrowed: number,
	/**  Отложено (факт по накоплениям). */
	saved: number,
};

/**  Строка листа «Сводка» за месяц. */
export type MonthSummaryDto = {
	month: string,
	income: number,
	incomeReceived: number,
	incomeExpected: number,
	expenses: number,
	savings: number,
	/**  Долги, взятые в месяце: источник денег. */
	borrowed: number,
	/**  Оплаченные погашения месяца: выплата, не расход. */
	repaid: number,
	free: number,
	freeCum: number,
	savingsCum: number,
	/**  Норма сбережений в базисных пунктах; `None` без дохода. */
	savingsRateBp: number | null,
	unspentRate: number | null,
	savingsPlanRateBp: number,
	/**  Процент плана больше нуля и отличается от нормы из настроек. */
	savingsPlanOffNorm: boolean,
	savingsPlan: number,
	savingsGap: number,
	perWeek: number,
	corridor: CorridorDto,
	topUpToMin: number,
	topUpToNorm: number,
	byStatus: StatusAmountsDto,
	byKind: KindAmountsDto,
};

export type PeriodPresetDto = "ytd" | "last12" | "current_month" | "all";

/**  Итог распределения дохода. */
export type PlanBalanceDto = "empty" | "balanced" | "unallocated" | "over";

/**  Погашение долга в плане месяца: отдельная строка, отмечается «Оплачено» как трата. */
export type PlanRepaymentDto = {
	paymentId: number,
	debtId: number,
	lender: string,
	amount: number,
	status: DebtPaymentStatusDto,
};

/**  Строка «план → факт» по статье или накоплению. */
export type PlanRowDto = {
	categoryId: number,
	plan: number,
	fact: number,
	/**  `fact − plan`: положительное — потрачено больше плана. */
	deviation: number,
};

/**  Ввод мастера первого месяца: доходы, суммы по статьям, план накоплений. */
export type PlanWizardInputDto = {
	incomes: WizardIncomeDto[],
	lines: WizardLineDto[],
	savings: WizardSavingsDto[],
};

/**  Содержимое `ui-prefs.json`: только оболочка, никаких данных бюджета. */
export type Prefs = {
	theme: Theme,
	locale: string,
	/**  Масштаб интерфейса в процентах, 90–125. */
	uiScale: number,
	reducedMotion: ReducedMotion,
	/**
	 *  Копия `security.autolock_minutes` для экрана входа: настройка лежит в зашифрованной БД и
	 *  до входа недоступна. Пишет бэкенд при входе и при смене настройки; не секрет. `0` — никогда,
	 *  `None` — ещё не известна (файл создан старой версией): экран входа тогда ничего не пишет.
	 */
	autolockMinutes: number | null,
	/**  Знакомство при первом запуске пройдено или пропущено. */
	introDone: boolean,
};

export type PrefsPatch = {
	theme?: Theme | null,
	locale?: string | null,
	uiScale?: number | null,
	reducedMotion?: ReducedMotion | null,
	introDone?: boolean | null,
};

/**  Причина мягкой подсказки: токен с известным ключом не распознан и ушёл в текст. */
export type QueryHintDto = "empty_value" | "unknown_value" | "bad_amount" | "bad_month" | "negation_unsupported";

export type QueryHintSpanDto = {
	start: number,
	end: number,
	hint: QueryHintDto,
};

/**  Разбор строки запроса без выборки данных: чипы токенов и подсказки. */
export type QueryParseDto = {
	spans: TokenSpanDto[],
	hints: QueryHintSpanDto[],
};

/**  Recovery-код показывается один раз сразу после создания. */
export type RecoveryCodeDto = {
	recoveryCode: string,
};

export type ReducedMotion = "system" | "on";

export type SavedDto = {
	saved: boolean,
};

export type SavedFilterDto = {
	id: number,
	name: string,
	query: string,
	screen: FilterScreenDto,
};

/**  Месяц фактического накопления. */
export type SavingsMonthDto = {
	month: string,
	savings: number,
	coupon: number,
	balance: number,
	deposited: number,
	couponIncome: number,
};

/**  Раздел «Сбережения» за год. */
export type SavingsOverviewDto = {
	year: number,
	/**  Самый ранний год, с которого у накоплений есть данные (нижняя граница переключателя года). */
	firstYear: number,
	items: AccumulationDto[],
	/**  Сумма балансов накоплений на конец декабря. */
	totalBalance: number,
	/**  План сбережений на декабрь года просмотра (сумма планов накоплений). */
	monthPlan: number,
	totalScenarios: ForecastScenarioDto[],
	totalForecastChart: ChartDataDto,
};

/**  Параметры накопления: ставка 0 — простое накопление без купонов. */
export type SavingsParamsDto = {
	annualRateBp: number,
	taxBp: number,
	initialBalance: number,
	initialMonth: string,
};

/**  Как задан план накопления в месяц. */
export type SavingsPlanKindDto = "percent" | "fixed";

/**  Строка графика на входе: месяц и сумма. */
export type SchedulePaymentDto = {
	month: string,
	amount: number,
};

/**  Ответ `debt_schedule_preview`: строки графика и их сумма (считает Rust). */
export type SchedulePreviewDto = {
	rows: SchedulePaymentDto[],
	total: number,
};

/**  Ответ палитры. `request_id` возвращается как есть: UI отбрасывает устаревшие ответы. */
export type SearchResultDto = {
	requestId: number,
	spans: TokenSpanDto[],
	hints: QueryHintSpanDto[],
	transactions: TransactionGroupDto,
	incomes: IncomeGroupDto,
	categories: CategoryHitDto[],
	months: MonthHitDto[],
};

/**  Пароль или recovery-код с фронтенда. В `Debug` и логи не попадает. */
export type Secret = string;

/**  Период ряда месяцев для графика «Обзора». */
export type SeriesRangeDto = 
/**  Двенадцать месяцев года выбранного месяца. */
"year" | 
/**  Двенадцать месяцев, заканчивая выбранным. */
"12m" | 
/**  Все месяцы с данными (не дальше десяти лет назад). */
"all";

/**  Настройки, которые редактирует пользователь. */
export type SettingsDto = {
	savingsMinBp: number,
	savingsNormBp: number,
	savingsMaxBp: number,
	weeksPerMonth: number,
	autolockMinutes: number,
	lockOnMinimize: boolean,
	backupAutoDaily: boolean,
};

export type SettingsPatchDto = {
	savingsMinBp?: number | null,
	savingsNormBp?: number | null,
	savingsMaxBp?: number | null,
	weeksPerMonth?: number | null,
	autolockMinutes?: number | null,
	lockOnMinimize?: boolean | null,
	backupAutoDaily?: boolean | null,
};

export type StatusAmountsDto = {
	paid: number,
	debt: number,
	unplanned: number,
	planned: number,
	/**  Сумма по всем статусам. */
	total: number,
	/**  Доли статусов в сумме, базисные пункты (0 при нулевой сумме). */
	shareBp: StatusSharesDto,
};

/**  Доли статусов в общей сумме, базисные пункты (10 000 = 100 %). */
export type StatusSharesDto = {
	paid: number,
	debt: number,
	unplanned: number,
	planned: number,
};

/**
 *  Тема ОС изменилась. WebView2 может не передавать её странице через `prefers-color-scheme`,
 *  поэтому режим «системная» берёт тему у окна и следует этому событию.
 */
export type SystemThemeChanged = {
	dark: boolean,
};

export type TagDto = {
	id: number,
	name: string,
};

export type Theme = "system" | "light" | "dark";

export type TitleSuggestionDto = {
	title: string,
	categoryId: number,
	uses: number,
};

/**  Чем распознан токен запроса; UI красит токены по этому полю. */
export type TokenKindDto = "text" | "amount" | "status" | "category" | "kind" | "month" | "tag" | "source" | "record";

/**  Токен запроса: `start..end` — позиции в символах (не в UTF-16 и не в байтах). */
export type TokenSpanDto = {
	start: number,
	end: number,
	kind: TokenKindDto,
	negated: boolean,
};

export type TransactionDto = {
	id: number,
	month: string,
	date: string | null,
	categoryId: number,
	title: string,
	amount: number,
	status: TxStatusDto,
	comment: string | null,
	tagIds: number[],
};

/**  Группа трат: `total` и `sum` — по всем совпадениям, `items` — первые строки. */
export type TransactionGroupDto = {
	total: number,
	sum: number,
	items: TransactionHitDto[],
};

export type TransactionHitDto = {
	id: number,
	title: string,
	categoryId: number,
	category: string,
	month: string,
	date: string | null,
	amount: number,
	status: TxStatusDto,
};

/**  Новая трата. Если задана `date`, её месяц должен совпадать с `month`. */
export type TransactionInput = {
	month: string,
	date: string | null,
	categoryId: number,
	title: string,
	amount: number,
	status: TxStatusDto,
	comment: string | null,
};

/**  Правка траты: отсутствующее поле не меняется; `date`/`comment: null` очищают значение. */
export type TransactionPatchDto = TransactionPatchDto_Serialize | TransactionPatchDto_Deserialize;

/**  Правка траты: отсутствующее поле не меняется; `date`/`comment: null` очищают значение. */
export type TransactionPatchDto_Deserialize = {
	month?: string | null,
	date?: string | null,
	categoryId?: number | null,
	title?: string | null,
	amount?: number | null,
	status?: TxStatusDto | null,
	comment?: string | null,
};

/**  Правка траты: отсутствующее поле не меняется; `date`/`comment: null` очищают значение. */
export type TransactionPatchDto_Serialize = {
	month: string | null,
	date: string | null,
	categoryId: number | null,
	title: string | null,
	amount: number | null,
	status: TxStatusDto | null,
	comment: string | null,
};

/**
 *  Полный список трат по запросу для таблицы «Расходы»; `total` и `sum` — по всем
 *  совпадениям, `truncated` — строк больше, чем отдано.
 */
export type TransactionSearchDto = {
	requestId: number,
	spans: TokenSpanDto[],
	hints: QueryHintSpanDto[],
	total: number,
	sum: number,
	truncated: boolean,
	items: TransactionDto[],
};

export type TxStatusDto = "paid" | "debt" | "unplanned" | "planned";

/**  Состояние до и после правки: по `previous` UI делает отмену. */
export type TxUpdateResultDto = {
	current: TransactionDto,
	previous: TransactionDto,
};

/**  Хранилище заблокировано: фронтенд очищает stores с данными и уходит на `/lock`. */
export type VaultLocked = {
	reason: LockReason,
};

export type VaultStatusDto = {
	exists: boolean,
	locked: boolean,
	/**  Сколько мс ещё ждать до следующей попытки входа; `0` — можно вводить. */
	retryAfterMs: number,
	/**  Перенос данных из папки прежнего идентификатора не удался: его можно повторить. */
	migrationFailed: boolean,
};

/**  Ожидаемое поступление в мастере первого месяца. */
export type WizardIncomeDto = {
	sourceName: string,
	amount: number,
};

/**  Плановая сумма по статье расходов. */
export type WizardLineDto = {
	categoryId: number,
	amount: number,
};

export type WizardSavingsDto = {
	categoryId: number,
	plan: WizardSavingsPlanDto,
};

/**  План накопления: процент от дохода или фиксированная сумма. */
export type WizardSavingsPlanDto = { kind: "percent"; rateBp: number } | { kind: "fixed"; amount: number };

/**  Все строки листа «Сводка» за год: месяцы, итоги, категории и баланс бюджета. */
export type YearSummaryDto = {
	year: number,
	months: MonthSummaryDto[],
	income: number,
	expenses: number,
	savings: number,
	free: number,
	monthsWithData: number,
	avgIncome: number,
	avgExpenses: number,
	avgSavings: number,
	avgFree: number,
	savingsRate: number | null,
	byStatus: StatusAmountsDto,
	byKind: KindAmountsDto,
	categories: CategoryYearRowDto[],
	balance: BudgetBalanceDto,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

